<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(NgeoltxFramework)</TargetFramework>
    <AssemblyName>ngeoltx</AssemblyName>
    <RootNamespace>Ngeoltx.App</RootNamespace>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaNameGeneratorIsEnabled>true</AvaloniaNameGeneratorIsEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Ngeoltx.Engine/Ngeoltx.Engine.csproj" />
    <ProjectReference Include="../Ngeoltx.Drivers/Ngeoltx.Drivers.csproj" />
  </ItemGroup>
</Project>
