<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(NgeoltxFramework)</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ngeoltx.Engine/Ngeoltx.Engine.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="9.0.0" />
  </ItemGroup>
</Project>
